### ISSUE TITLE
[IoT Device][IoT Platform] Povezati ESP32 i ThingsBoard

### ISSUE THREAD

**Issue by NEYMARKO** [evid3nt/System-For-Monitoring-Class-Attendance#11]
- povezati ESP32 i ThingsBoard MQTT-om 
- vidjeti kako definirati topicse, kako ćemo ih modelirati, definirati path, i sl. 
- vidjeti što ESP32 treba slati za auth prema MQTT brokeru (ACCESS KEY, CA CERTIFICATE?)
- definirati koje podatke treba ESP32 slati i u kojem formatu (JSON?)

Koristan url: https://thingsboard.io/docs/reference/mqtt-api/

**Comment by Karlito16** [comment]
Napravljeno:

- povezani ESP32 i ThingsBoard MQTT-om
- topicse za telemetry definirali ovako: ~`classrooms/{učionica}/{ulaz*}`~, npr.:
  - ~`classrooms/b4/a`~
  - ~`classrooms/b4/b`~
  - ~`classrooms/a-201`~
- ESP32, da bi slao podatke, treba za autorizaciju koristiti `access_token` dobiven od ThingsBoard platforme (svaki device ima unique token)
- još dogovaramo JSON format, ali okvirno će biti nešto tipa ovoga:
```
{
    "cardId": "47-34-124-44"
}
```
  - trebamo vidjet kako pratiti vrijeme skeniranja, više objasnimo u utorak na sastanku

**Comment by Karlito16** [comment]
> Napravljeno:
> 
>     * povezani ESP32 i ThingsBoard MQTT-om
> 
>     * topicse za telemetry definirali ovako: `classrooms/{učionica}/{ulaz*}`, npr.:
>       
>       * `classrooms/b4/a`
>       * `classrooms/b4/b`
>       * `classrooms/a-201`
> 
>     * ESP32, da bi slao podatke, treba za autorizaciju koristiti `access_token` dobiven od ThingsBoard platforme (svaki device ima unique token)
> 
>     * još dogovaramo JSON format, ali okvirno će biti nešto tipa ovoga:
> 
> 
> ```
> {
>     "cardId": 47-34-124-44
> }
> ```
> 
>     * trebamo vidjet kako pratiti vrijeme skeniranja, više objasnimo u utorak na sastanku

**MQTT topic i MQTT payload ažurirani - vidjeti ovo:** https://github.com/evid3nt/System-For-Monitoring-Class-Attendance/issues/3#issuecomment-2147391751
