### ISSUE TITLE
[WebApp] Backend

### ISSUE THREAD

**Issue by bk53409** [evid3nt/System-For-Monitoring-Class-Attendance#5]
Odabran framework za Backend je .dotnet v6.0 i c#

Napravljeni su osnovne operacije za svaki objekt/entitet. Trenutno se koristi inmemory baza jer imam nekih problema s pgadminom gdje mi ne želi uopće učitat lokalni server - to ću svakako probat riješit, ali ako ne uspijem do demonstracije da imamo bar ovo. Tko ne zna kako inmemory baza funkcionira -> funkcionira normalno kao i obična samo se pri svakom pokretanju inicijalizira ponovno i ne spremaju se stare vrijednosti nakon što se projekt ugasi.

Svaki api ima svoju putanju koja ide api/_imeObjekta_ ili api/_imeObjekta_/_{id}_ (npr. api/Lecture/2b00c94c-b601-4253-8bac-86b2d2b64392) 

**JOŠ NIJE PUSHANO jer mi iz nekog razloga neda (Karlo kontaktiran)**

Zašto ove lude brojke i slova kod id-a --> e pa to je Guid tip podatka koji će se koristiti umjesto int-a za id-eve (prednost -> nikad se neće genrirati dva ista guida i sada ne ovisimo o bazi za generiranje ključeva) [https://www.techtarget.com/searchwindowsserver/definition/GUID-global-unique-identifier#:~:text=A%20GUID%20(globally%20unique%20identifier,on%20a%20computer%20or%20network.]

### Objekti i njihovi atributi:
Classroom

- Guid Id
- string ClassroomName

Course

- Guid Id
- string CourseName

Lecture

- Guid Id
- DateTime LectureStart
- DateTime LectureEnd
- Guid CoursId (foreing key)
- Guid ClassroomId (foreing key)

Telemetry

- Guid Id
- DateTime ScanTime
- Guid UserId (foreing key)
- Guid ClassroomId (foreing key)

User

- Guid Id
- string FirstName
- string LastName
- UserRole UserRole (enum) --> u bazi string (postoji UserDTO)

UsersCourse

- Guid Id
- Guid UserId
- Guid CourseId

**Comment by Karlito16** [comment]
Super! 

Napravi pull request iz svog brancha pa to merđamo u develop.

P.S. Model izgleda skroz okej, jedino će vjv trebat dodat novi stupac u User tablicu, nešto tipa UserCardKey, jer kad student skenria svoj privjesak ili karticu, na uređaju se to manifestira kao neki uuid isto, pa će trebat imat taj podatak da znamo tko je taj user s tim privjeskom. Sad ću imat call sa Prosom da povežemo device i platformu.

Super posao! 👍
